[project]
name = "mkdocs_simple_blog"
version = "0.2.0"
authors = [
  { name="Saket Sinha", email="saket.sinha89@gmail.com" },
]
license = {file = "LICENSE"}
description = "Mkdocs Blog Theme"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"mkdocs"
]
classifiers = [
  'Development Status :: 4 - Beta',
  "Operating System :: OS Independent",
  'Intended Audience :: Developers',
  'Natural Language :: English',
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/disdi/clic-in-litex"
Issues = "https://github.com/disdi/clic-in-litex/issues"
Repository = "https://github.com/disdi/clic-in-litex"
Documentation = "https://github.com/disdi/clic-in-litex/blob/master/README.md"

[tool.poetry]
name = "mkdocs_simple_blog"
version = "0.2.0"
description = "Mkdocs Blog Theme"
authors = ["Saket Sinha <saket.sinha89@gmail.com>"]
readme = "README.md"
license = "MIT"
package-mode = true
homepage = "https://github.com/disdi/clic-in-litex"
documentation = "https://github.com/disdi/clic-in-litex"
repository = "https://github.com/disdi/clic-in-litex"
classifiers = [
  'Development Status :: 5 - Production/Stable',
  "Operating System :: OS Independent",
  'Intended Audience :: Developers',
  'Natural Language :: English',
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = ">=3.9.0"
mkdocs = "^1.6.1"

[tool.poetry.group.dev.dependencies]
build = "^1.2.2.post1"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
